### PR TITLE
Feature: download samples as encrypted zip

### PR DESCRIPTION
**Pull request by 3c7**
Proposal for #13.

### CODE REVIEW

**Comment by 3c7** [comment]
Using 7z, because it is a dependency of FAME and python has no built-in tools for encrypting zip-archives.

**Comment by gaelmuller** [comment]
Actually 7z is not a dependency of FAME at the moment, it is a dependency for some of the antivirus modules. Is there any other way we can do this ? I am not comfortable with adding 7z as a global dependency.

On another matter, we will not accept the PR as it is because we want to keep the ability to directly download the sample. This would be acceptable as an additional option though ("Download / Download as zip").

**Comment by 3c7** [comment]
Ooops. Just remembered I was prompted to install 7z when I first started the worker, so I assumed it is a dependency of FAME.

Don't know, if there are other possibilites to encrypt a zip with python, will find out about it. 🔍

**Comment by 3c7** [comment]
Possible variants (extending the list, if I find other solutions):
- [ ] use 7z
- [ ] use pyminizip (which has zlib as dependency)

**Pull request closed without merging**
